"""Domain contracts and stage result models for internal orchestration pipeline."""

from __future__ import annotations

from enum import StrEnum
from typing import Any
from uuid import UUID, uuid4

from pydantic import Field

from app.schemas.base import SchemaModel
from app.schemas.context import Entity, Intent, NavigationState
from app.schemas.planner import PlannerResponse


class PipelineResultStatus(StrEnum):
    """Execution status categories produced by the orchestration pipeline."""

    SUCCEEDED = "succeeded"
    CLARIFICATION_REQUIRED = "clarification_required"
    AUTHENTICATION_REQUIRED = "authentication_required"
    HUMAN_HANDOFF = "human_handoff"
    PARTIAL_COMPLETION = "partial_completion"
    FAILED = "failed"


class IntentResult(SchemaModel):
    """Strongly typed domain output from Intent Engine stage."""

    intent: Intent | None = Field(default=None, description="Classified intent model.")
    intent_type: str = Field(default="general", description="Intent type name.")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Classification confidence.")
    entities: list[Entity] = Field(default_factory=list, description="Extracted entities.")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Intent metadata.")


class Plan(SchemaModel):
    """Strongly typed domain output from Planner stage."""

    plan_id: UUID = Field(default_factory=uuid4, description="Unique plan identifier.")
    planner_response: PlannerResponse | None = Field(default=None, description="Planner response details.")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Planner metadata.")


class ExecutionResult(SchemaModel):
    """Strongly typed domain output from Execution Engine stage."""

    success: bool = Field(default=True, description="Whether execution succeeded.")
    output: str = Field(default="", description="Text output generated by downstream execution.")
    navigation_state: NavigationState | None = Field(default=None, description="Updated navigation state.")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Execution metadata.")


class PipelineResult(SchemaModel):
    """Composite domain result before final response formatting."""

    status: PipelineResultStatus = Field(default=PipelineResultStatus.SUCCEEDED, description="Overall pipeline status.")
    execution_result: ExecutionResult | None = Field(default=None, description="Execution result stage output.")
    intent_result: IntentResult | None = Field(default=None, description="Intent detection stage output.")
    plan: Plan | None = Field(default=None, description="Planner stage output.")
    content: str = Field(default="", description="Generated assistant message text.")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Pipeline result metadata.")
