import React, { useEffect, useRef } from 'react';
import { motion, type Variants } from 'framer-motion';
import type { SaarthiState } from './SaarthiContext';

export interface SaarthiAvatarProps {
  state?: SaarthiState;
  minimized?: boolean;
  onClick?: () => void;
  className?: string;
  isTtsPlaying?: boolean;
  ttsPlaybackId?: number;
  isGreetingTtsSpeaking?: boolean;
}

const avatarAssets = {
  idle: '/assets/saarthi/idle-avatar.png',
  greeting: '/assets/saarthi/greeting-avatar.png',
  listening: '/assets/saarthi/listening-avatar.png',
  thinking: '/assets/saarthi/thinking-avatar.png',
  speaking: '/assets/saarthi/talking-avatar.webm',
} as const;

/**
 * Framer Motion Variant Map for Saarthi Digital Human Avatar Body
 */
export const saarthiAvatarVariants: Variants = {
  hidden: {
    opacity: 0,
    scale: 0.9,
    rotate: 0,
    y: 0,
  },
  enter: {
    opacity: 1,
    scale: 0.92,
    rotate: 0,
    y: 0,
    transition: {
      duration: 0.6,
      ease: [0.16, 1, 0.3, 1], // easeOutExpo
    },
  },
  greeting: {
    opacity: 1,
    scale: 1,
    rotate: [0, 10, 0], // Gentle 10-degree bow / hands joined gesture tilt
    y: [0, 4, 0],
    transition: {
      duration: 0.7,
      ease: [0.65, 0, 0.35, 1], // easeInOutCubic
    },
  },
  namaste: {
    opacity: 1,
    scale: [1, 0.92, 1.08, 1],
    rotate: [0, 8, -4, 0],
    y: [0, 6, -2, 0],
    transition: {
      duration: 1.5,
      ease: [0.65, 0, 0.35, 1],
    },
  },
  idle: {
    opacity: 1,
    scale: [1, 1.03, 1],
    y: [0, -5, 0],
    rotate: 0,
    transition: {
      duration: 3.8,
      repeat: Infinity,
      ease: 'easeInOut',
    },
  },
  listening: {
    opacity: 1,
    scale: 1.06,
    rotate: -3,
    transition: {
      duration: 1.2,
      repeat: Infinity,
      repeatType: 'reverse',
      ease: 'easeInOut',
    },
  },
  thinking: {
    opacity: 1,
    y: [-6, 6, -6],
    transition: {
      duration: 2.2,
      repeat: Infinity,
      ease: 'easeInOut',
    },
  },
  speaking: {
    opacity: 1,
    scale: [1, 1.05, 1.01, 1.04, 1],
    transition: {
      duration: 0.85,
      repeat: Infinity,
      ease: 'easeInOut',
    },
  },
  minimized: {
    scale: 0.46,
    opacity: 1,
    transition: {
      duration: 0.6,
      ease: [0.16, 1, 0.3, 1],
    },
  },
};

/**
 * SaarthiAvatar - Visual Shell for AI Conversational Agent Body
 *
 * Plug-and-play component: When the final SVG avatar sheets are generated by the design team,
 * only the inner SVG graphics inside this file will be updated.
 */
export const SaarthiAvatar: React.FC<SaarthiAvatarProps> = ({
  state = 'idle',
  minimized = false,
  onClick,
  className = '',
  isTtsPlaying = false,
  ttsPlaybackId = 0,
  isGreetingTtsSpeaking = false,
}) => {
  const variantKey = minimized ? 'minimized' : state;
  const mediaStyle: React.CSSProperties = {
    width: 'auto',
    height: 'auto',
    maxWidth: minimized ? '300px' : 'min(70vw, 320px)',
    maxHeight: minimized ? '300px' : 'min(38vh, 420px)',
    objectFit: 'contain',
  };
  const videoRef = useRef<HTMLVideoElement>(null);
  const isTalking = state === 'speaking' || (state === 'greeting' && isGreetingTtsSpeaking);
  const showTalkingVideo = isTalking && isTtsPlaying;
  const imageSrc = state === 'greeting' || state === 'namaste'
    ? avatarAssets.greeting
    : state === 'listening'
      ? avatarAssets.listening
      : state === 'thinking'
        ? avatarAssets.thinking
        : avatarAssets.idle;

  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;

    if (!isTalking || !isTtsPlaying) {
      video.pause();
      video.currentTime = 0;
      return;
    }

    video.currentTime = 0;
    void video.play().catch(() => {
      // Playback remains safely muted; browser policy may still require a user gesture.
    });
  }, [isTalking, isTtsPlaying, ttsPlaybackId]);

  return (
    <div
      className={`relative flex items-center justify-center cursor-pointer select-none ${className}`}
      onClick={onClick}
      role="button"
      tabIndex={0}
      aria-label={`Saarthi Avatar Body (${state} state)`}
    >
      {/* Saarthi avatar asset shell */}
      <motion.div
        variants={saarthiAvatarVariants}
        initial={variantKey === 'enter' ? 'hidden' : false}
        animate={variantKey}
        className="relative flex items-center justify-center"
      >
        <div className="grid place-items-center">
          <img
            src={imageSrc}
            alt={`Saarthi ${state}`}
            className={`col-start-1 row-start-1 block object-contain transition-opacity duration-150 ${showTalkingVideo ? 'opacity-0' : 'opacity-100'}`}
            style={mediaStyle}
          />
          <video
            ref={videoRef}
            src={avatarAssets.speaking}
            muted
            loop
            playsInline
            preload="auto"
            className={`col-start-1 row-start-1 block object-contain transition-opacity duration-150 ${showTalkingVideo ? 'opacity-100' : 'opacity-0'}`}
            style={mediaStyle}
            aria-label="Saarthi speaking"
          />
        </div>
      </motion.div>
    </div>
  );
};
