"""Automatic frontend route discovery engine for MantraSetu AgentOS.

This module provides RouteDiscoveryEngine for scanning frontend React + Wouter route configurations
and dynamically discovering rich page metadata, parameters, workflow types, auth requirements, permissions,
feature flags, visible regions, and page capabilities.
"""

from __future__ import annotations

import logging
from typing import Any

from app.navigation.models import NavigationNodeType, WebsiteNode

logger = logging.getLogger(__name__)

DEFAULT_FRONTEND_ROUTES: list[dict[str, Any]] = [
    {
        "path": "/",
        "name": "Home",
        "page_type": "PORTAL",
        "semantic_label": "MantraSetu Spiritual Home Portal",
        "description": "Main landing portal for Vedic pujas, astrology, and auspicious muhurat discovery.",
        "parent": None,
        "children": ["/services", "/puja", "/kundali", "/muhurat", "/login", "/dashboard"],
        "breadcrumbs": ["Home"],
        "workflow": None,
        "workflow_step": None,
        "parameters": [],
        "validation_rules": {},
        "requires_auth": False,
        "permissions": [],
        "feature_flags": ["ENABLE_HOME_BANNER"],
        "allowed_transitions": ["/services", "/puja", "/kundali", "/muhurat", "/login", "/signup", "/dashboard"],
        "previous_routes": [],
        "next_routes": ["/services", "/puja", "/kundali", "/muhurat"],
        "shortcut_routes": ["/puja", "/kundali"],
        "recovery_routes": ["/"],
        "page_capabilities": ["SEARCH_SERVICES", "FEATURED_PUJAS", "DAILY_HOROSCOPE_PREVIEW"],
        "supported_ai_actions": ["NAVIGATE", "SEARCH", "CLICK"],
        "visible_regions": ["header", "hero_banner", "featured_pujas_grid", "quick_services_row", "footer"],
        "primary_actions": ["BOOK_PUJA", "CHECK_KUNDALI", "CALCULATE_MUHURAT"],
        "secondary_actions": ["VIEW_SERVICES", "LOGIN"],
        "forms": [],
        "buttons": ["btn_book_puja", "btn_check_kundali", "btn_find_muhurat", "btn_login"],
        "dropdowns": ["dd_language"],
        "filters": [],
        "cards": ["card_puja_popular", "card_horoscope_daily", "card_muhurat_today"],
        "tables": [],
        "dialogs": [],
        "tabs": [],
        "accordions": [],
        "search_boxes": ["search_main"],
        "uploads": [],
        "downloads": [],
        "metadata_version": "4.1",
        "updated_at": "2026-07-31T22:50:00Z",
    },
    {
        "path": "/services",
        "name": "Services",
        "page_type": "CATALOG",
        "semantic_label": "All Spiritual Services Catalog",
        "description": "Comprehensive list of spiritual services offered by MantraSetu.",
        "parent": "/",
        "children": ["/puja", "/kundali"],
        "breadcrumbs": ["Home", "Services"],
        "workflow": None,
        "workflow_step": None,
        "parameters": [],
        "validation_rules": {},
        "requires_auth": False,
        "permissions": [],
        "feature_flags": [],
        "allowed_transitions": ["/", "/puja", "/kundali"],
        "previous_routes": ["/"],
        "next_routes": ["/puja", "/kundali"],
        "shortcut_routes": ["/puja"],
        "recovery_routes": ["/"],
        "page_capabilities": ["FILTER_SERVICES", "CATEGORIZE_SERVICES"],
        "supported_ai_actions": ["NAVIGATE", "FILTER", "SELECT"],
        "visible_regions": ["header", "filter_sidebar", "services_list", "footer"],
        "primary_actions": ["SELECT_SERVICE"],
        "secondary_actions": ["GO_HOME"],
        "forms": [],
        "buttons": ["btn_filter_category"],
        "dropdowns": ["dd_category"],
        "filters": ["filter_puja_type", "filter_price"],
        "cards": ["card_service_item"],
        "tables": [],
        "dialogs": [],
        "tabs": [],
        "accordions": [],
        "search_boxes": [],
        "uploads": [],
        "downloads": [],
        "metadata_version": "4.1",
        "updated_at": "2026-07-31T22:50:00Z",
    },
    {
        "path": "/puja",
        "name": "PujaCatalog",
        "page_type": "CATALOG",
        "semantic_label": "Pujas & Vedic Rituals Catalog",
        "description": "Explore and select Vedic pujas for peace, prosperity, and dosha remedies.",
        "parent": "/",
        "children": ["/puja/[id]"],
        "breadcrumbs": ["Home", "Pujas"],
        "workflow": "PUJA_BOOKING",
        "workflow_step": "SELECT_PUJA",
        "parameters": [],
        "validation_rules": {},
        "requires_auth": False,
        "permissions": [],
        "feature_flags": ["ENABLE_DOSHA_FILTER"],
        "allowed_transitions": ["/", "/puja/[id]"],
        "previous_routes": ["/"],
        "next_routes": ["/puja/[id]"],
        "shortcut_routes": ["/puja/[id]"],
        "recovery_routes": ["/"],
        "page_capabilities": ["SEARCH_PUJAS", "FILTER_BY_DEITY", "FILTER_BY_DOSHA"],
        "supported_ai_actions": ["NAVIGATE", "FILTER", "SEARCH", "SELECT"],
        "visible_regions": ["header", "search_bar", "deity_tabs", "pujas_grid", "footer"],
        "primary_actions": ["VIEW_PUJA_DETAIL"],
        "secondary_actions": ["FILTER_PUJAS"],
        "forms": ["form_search_puja"],
        "buttons": ["btn_search", "btn_view_puja"],
        "dropdowns": ["dd_deity", "dd_purpose"],
        "filters": ["filter_popular", "filter_dosha_remedy"],
        "cards": ["card_puja_item"],
        "tables": [],
        "dialogs": [],
        "tabs": ["tabs_puja_categories"],
        "accordions": [],
        "search_boxes": ["input_puja_query"],
        "uploads": [],
        "downloads": [],
        "metadata_version": "4.1",
        "updated_at": "2026-07-31T22:50:00Z",
    },
    {
        "path": "/puja/[id]",
        "name": "PujaDetail",
        "page_type": "DETAIL",
        "semantic_label": "Puja Packages & Ritual Details View",
        "description": "Detailed view of ritual inclusions, package pricing, and samagri options.",
        "parent": "/puja",
        "children": ["/booking"],
        "breadcrumbs": ["Home", "Pujas", "Puja Details"],
        "workflow": "PUJA_BOOKING",
        "workflow_step": "VIEW_DETAIL",
        "parameters": ["id"],
        "validation_rules": {"id": "REQUIRED_NUMERIC"},
        "requires_auth": False,
        "permissions": [],
        "feature_flags": [],
        "allowed_transitions": ["/puja", "/booking"],
        "previous_routes": ["/puja"],
        "next_routes": ["/booking"],
        "shortcut_routes": ["/booking"],
        "recovery_routes": ["/puja"],
        "page_capabilities": ["VIEW_BENEFITS", "SELECT_SAMAGRI_TIER", "READ_REVIEWS"],
        "supported_ai_actions": ["NAVIGATE", "SELECT_PACKAGE", "START_BOOKING"],
        "visible_regions": ["header", "puja_hero_summary", "package_pricing_cards", "samagri_table", "footer"],
        "primary_actions": ["START_BOOKING"],
        "secondary_actions": ["BACK_TO_CATALOG"],
        "forms": [],
        "buttons": ["btn_proceed_booking", "btn_share"],
        "dropdowns": ["dd_package_tier"],
        "filters": [],
        "cards": ["card_package_basic", "card_package_premium"],
        "tables": ["table_ritual_inclusions"],
        "dialogs": [],
        "tabs": [],
        "accordions": ["accordion_faq"],
        "search_boxes": [],
        "uploads": [],
        "downloads": [],
        "metadata_version": "4.1",
        "updated_at": "2026-07-31T22:50:00Z",
    },
    {
        "path": "/booking",
        "name": "Booking",
        "page_type": "WORKFLOW_STEP",
        "semantic_label": "Puja Date & Package Selection Step",
        "description": "Choose date, time slot, and location details for performing the puja.",
        "parent": "/puja/[id]",
        "children": ["/pandit", "/payment"],
        "breadcrumbs": ["Home", "Pujas", "Details", "Booking"],
        "workflow": "PUJA_BOOKING",
        "workflow_step": "SELECT_DATE",
        "parameters": ["puja_id", "date"],
        "validation_rules": {"puja_id": "REQUIRED", "date": "REQUIRED_FUTURE_DATE"},
        "requires_auth": False,
        "permissions": [],
        "feature_flags": [],
        "allowed_transitions": ["/puja/[id]", "/pandit", "/payment", "/login"],
        "previous_routes": ["/puja/[id]"],
        "next_routes": ["/pandit", "/payment"],
        "shortcut_routes": ["/payment"],
        "recovery_routes": ["/puja/[id]"],
        "page_capabilities": ["CALENDAR_PICKER", "TIME_SLOT_SELECTION", "LOCATION_INPUT"],
        "supported_ai_actions": ["NAVIGATE", "SELECT_DATE", "SELECT_TIME", "INPUT_ADDRESS"],
        "visible_regions": ["header", "booking_form_card", "date_picker_section", "summary_panel", "footer"],
        "primary_actions": ["SELECT_PANDIT", "PROCEED_TO_PAYMENT"],
        "secondary_actions": ["BACK_TO_DETAILS"],
        "forms": ["form_booking_details"],
        "buttons": ["btn_select_pandit", "btn_proceed_payment"],
        "dropdowns": ["dd_time_slot", "dd_samagri_option"],
        "filters": [],
        "cards": ["card_booking_summary"],
        "tables": [],
        "dialogs": [],
        "tabs": [],
        "accordions": [],
        "search_boxes": [],
        "uploads": [],
        "downloads": [],
        "metadata_version": "4.1",
        "updated_at": "2026-07-31T22:50:00Z",
    },
    {
        "path": "/pandit",
        "name": "PanditSelection",
        "page_type": "WORKFLOW_STEP",
        "semantic_label": "Vedic Priest & Scholar Choice Step",
        "description": "Select an experienced Vedic Pandit based on language, experience, and ratings.",
        "parent": "/booking",
        "children": ["/payment"],
        "breadcrumbs": ["Home", "Pujas", "Booking", "Pandit"],
        "workflow": "PUJA_BOOKING",
        "workflow_step": "SELECT_PANDIT",
        "parameters": [],
        "validation_rules": {},
        "requires_auth": False,
        "permissions": [],
        "feature_flags": ["ENABLE_PANDIT_RATINGS"],
        "allowed_transitions": ["/booking", "/payment"],
        "previous_routes": ["/booking"],
        "next_routes": ["/payment"],
        "shortcut_routes": ["/payment"],
        "recovery_routes": ["/booking"],
        "page_capabilities": ["PANDIT_LISTING", "LANGUAGE_FILTER", "AUTO_ASSIGN_PRIEST"],
        "supported_ai_actions": ["NAVIGATE", "SELECT_PANDIT", "FILTER_LANGUAGES"],
        "visible_regions": ["header", "pandit_cards_grid", "filter_bar", "footer"],
        "primary_actions": ["CHOOSE_PANDIT"],
        "secondary_actions": ["SKIP_PANDIT_CHOICE"],
        "forms": [],
        "buttons": ["btn_choose_pandit", "btn_auto_assign"],
        "dropdowns": ["dd_language_preference"],
        "filters": ["filter_experience", "filter_rating"],
        "cards": ["card_pandit_profile"],
        "tables": [],
        "dialogs": [],
        "tabs": [],
        "accordions": [],
        "search_boxes": [],
        "uploads": [],
        "downloads": [],
        "metadata_version": "4.1",
        "updated_at": "2026-07-31T22:50:00Z",
    },
    {
        "path": "/kundali-creation",
        "name": "Kundali",
        "page_type": "CALCULATOR",
        "semantic_label": "Vedic Kundali & Horoscope Generator",
        "description": "Generate birth chart and planetary position report with dosha remedies.",
        "parent": "/",
        "children": ["/puja/[id]"],
        "breadcrumbs": ["Home", "Kundali"],
        "workflow": "KUNDALI_ANALYSIS",
        "workflow_step": "INPUT_BIRTH_DATA",
        "parameters": [],
        "validation_rules": {"dob": "REQUIRED_DATE", "tob": "REQUIRED_TIME", "pob": "REQUIRED_STRING"},
        "requires_auth": False,
        "permissions": [],
        "feature_flags": [],
        "allowed_transitions": ["/", "/puja/[id]"],
        "previous_routes": ["/"],
        "next_routes": ["/puja/[id]"],
        "shortcut_routes": [],
        "recovery_routes": ["/"],
        "page_capabilities": ["HOROSCOPE_CALCULATION", "DOSHA_DETECTION", "REMEDY_RECOMMENDATION"],
        "supported_ai_actions": ["NAVIGATE", "INPUT_BIRTH_DETAILS", "GENERATE_REPORT"],
        "visible_regions": ["header", "birth_details_form", "chart_result_view", "remedies_grid", "footer"],
        "primary_actions": ["GENERATE_KUNDALI"],
        "secondary_actions": ["VIEW_DOSHA_REMEDIES"],
        "forms": ["form_birth_details"],
        "buttons": ["btn_generate_kundali", "btn_view_remedy_pujas"],
        "dropdowns": ["dd_gender", "dd_rashi"],
        "filters": [],
        "cards": ["card_kundali_summary", "card_dosha_report"],
        "tables": ["table_planetary_positions"],
        "dialogs": [],
        "tabs": [],
        "accordions": [],
        "search_boxes": [],
        "uploads": [],
        "downloads": [],
        "metadata_version": "4.1",
        "updated_at": "2026-07-31T22:50:00Z",
    },
    {
        "path": "/muhurat-finder",
        "name": "Muhurat",
        "page_type": "CALCULATOR",
        "semantic_label": "Shubh Muhurat Auspicious Timing Calculator",
        "description": "Find exact auspicious timings for marriages, housewarming, and business launch.",
        "parent": "/",
        "children": ["/booking", "/puja/[id]"],
        "breadcrumbs": ["Home", "Muhurat"],
        "workflow": "MUHURAT_SEARCH",
        "workflow_step": "SEARCH_MUHURAT",
        "parameters": [],
        "validation_rules": {"event_category": "REQUIRED"},
        "requires_auth": False,
        "permissions": [],
        "feature_flags": [],
        "allowed_transitions": ["/", "/booking", "/puja/[id]"],
        "previous_routes": ["/"],
        "next_routes": ["/booking"],
        "shortcut_routes": ["/booking"],
        "recovery_routes": ["/"],
        "page_capabilities": ["CHOGHADIYA_CALCULATOR", "PANCHANG_CALCULATOR"],
        "supported_ai_actions": ["NAVIGATE", "CALCULATE_TIME", "BOOK_MUHURAT_PUJA"],
        "visible_regions": ["header", "muhurat_search_form", "results_table", "footer"],
        "primary_actions": ["CALCULATE_SHUBH_TIME"],
        "secondary_actions": ["BOOK_MATCHING_PUJA"],
        "forms": ["form_muhurat_search"],
        "buttons": ["btn_calculate_muhurat", "btn_book_recommended"],
        "dropdowns": ["dd_event_category", "dd_city"],
        "filters": [],
        "cards": ["card_muhurat_timings"],
        "tables": ["table_choghadiya"],
        "dialogs": [],
        "tabs": [],
        "accordions": [],
        "search_boxes": [],
        "uploads": [],
        "downloads": [],
        "metadata_version": "4.1",
        "updated_at": "2026-07-31T22:50:00Z",
    },
    {
        "path": "/payment",
        "name": "Payment",
        "page_type": "CHECKOUT",
        "semantic_label": "Secure Payment Checkout Gateway",
        "description": "Review order summary and complete transaction via UPI, card, or netbanking.",
        "parent": "/booking",
        "children": ["/confirmation"],
        "breadcrumbs": ["Home", "Booking", "Payment"],
        "workflow": "PUJA_BOOKING",
        "workflow_step": "PAYMENT",
        "parameters": ["booking_id"],
        "validation_rules": {"booking_id": "REQUIRED"},
        "requires_auth": True,
        "permissions": ["PROCESS_PAYMENT"],
        "feature_flags": ["ENABLE_UPI", "ENABLE_CARDS"],
        "allowed_transitions": ["/booking", "/confirmation", "/login"],
        "previous_routes": ["/booking"],
        "next_routes": ["/confirmation"],
        "shortcut_routes": [],
        "recovery_routes": ["/login", "/booking"],
        "page_capabilities": ["PAYMENT_PROCESSING", "COUPON_VERIFICATION", "ORDER_SUMMARY"],
        "supported_ai_actions": ["NAVIGATE", "APPLY_COUPON", "SELECT_PAYMENT_METHOD"],
        "visible_regions": ["header", "payment_options_panel", "order_summary_sidebar", "footer"],
        "primary_actions": ["SUBMIT_PAYMENT"],
        "secondary_actions": ["APPLY_COUPON"],
        "forms": ["form_payment_checkout"],
        "buttons": ["btn_pay_now", "btn_apply_coupon"],
        "dropdowns": ["dd_payment_method"],
        "filters": [],
        "cards": ["card_order_total", "card_payment_options"],
        "tables": [],
        "dialogs": [],
        "tabs": [],
        "accordions": [],
        "search_boxes": [],
        "uploads": [],
        "downloads": [],
        "metadata_version": "4.1",
        "updated_at": "2026-07-31T22:50:00Z",
    },
    {
        "path": "/confirmation",
        "name": "Confirmation",
        "page_type": "RECEIPT",
        "semantic_label": "Order & Puja Booking Confirmation Receipt",
        "description": "Booking confirmation receipt with downloadable invoice and calendar sync.",
        "parent": "/payment",
        "children": [],
        "breadcrumbs": ["Home", "Confirmation"],
        "workflow": "PUJA_BOOKING",
        "workflow_step": "CONFIRMATION",
        "parameters": ["order_id"],
        "validation_rules": {"order_id": "REQUIRED"},
        "requires_auth": True,
        "permissions": [],
        "feature_flags": [],
        "allowed_transitions": ["/", "/dashboard"],
        "previous_routes": ["/payment"],
        "next_routes": ["/dashboard"],
        "shortcut_routes": ["/dashboard"],
        "recovery_routes": ["/dashboard"],
        "page_capabilities": ["RECEIPT_DOWNLOAD", "CALENDAR_SYNC", "BOOKING_TRACKING"],
        "supported_ai_actions": ["NAVIGATE", "DOWNLOAD_RECEIPT", "ADD_TO_CALENDAR"],
        "visible_regions": ["header", "success_banner", "booking_receipt_card", "footer"],
        "primary_actions": ["VIEW_DASHBOARD"],
        "secondary_actions": ["RETURN_HOME", "DOWNLOAD_RECEIPT"],
        "forms": [],
        "buttons": ["btn_view_dashboard", "btn_download_pdf"],
        "dropdowns": [],
        "filters": [],
        "cards": ["card_confirmation_details"],
        "tables": ["table_order_line_items"],
        "dialogs": [],
        "tabs": [],
        "accordions": [],
        "search_boxes": [],
        "uploads": [],
        "downloads": ["file_pdf_receipt"],
        "metadata_version": "4.1",
        "updated_at": "2026-07-31T22:50:00Z",
    },
    {
        "path": "/login",
        "name": "Login",
        "page_type": "AUTHENTICATION",
        "semantic_label": "User Sign In Portal",
        "description": "Sign in via phone OTP or password.",
        "parent": "/",
        "children": ["/dashboard", "/signup"],
        "breadcrumbs": ["Home", "Login"],
        "workflow": "AUTHENTICATION",
        "workflow_step": "USER_LOGIN",
        "parameters": ["redirect_to"],
        "validation_rules": {"phone_or_email": "REQUIRED", "password": "REQUIRED"},
        "requires_auth": False,
        "permissions": [],
        "feature_flags": ["ENABLE_OTP_LOGIN"],
        "allowed_transitions": ["/", "/signup", "/dashboard"],
        "previous_routes": ["/"],
        "next_routes": ["/dashboard"],
        "shortcut_routes": ["/signup"],
        "recovery_routes": ["/"],
        "page_capabilities": ["USER_LOGIN", "OTP_VERIFICATION", "PASSWORD_RESET"],
        "supported_ai_actions": ["NAVIGATE", "INPUT_CREDENTIALS", "SUBMIT_LOGIN"],
        "visible_regions": ["header", "login_card", "footer"],
        "primary_actions": ["SUBMIT_LOGIN"],
        "secondary_actions": ["GOTO_SIGNUP", "FORGOT_PASSWORD"],
        "forms": ["form_login"],
        "buttons": ["btn_submit_login", "btn_goto_signup"],
        "dropdowns": [],
        "filters": [],
        "cards": ["card_login_box"],
        "tables": [],
        "dialogs": [],
        "tabs": [],
        "accordions": [],
        "search_boxes": [],
        "uploads": [],
        "downloads": [],
        "metadata_version": "4.1",
        "updated_at": "2026-07-31T22:50:00Z",
    },
    {
        "path": "/signup",
        "name": "Signup",
        "page_type": "AUTHENTICATION",
        "semantic_label": "User Registration Account Portal",
        "description": "Create a new user account on MantraSetu.",
        "parent": "/login",
        "children": ["/dashboard"],
        "breadcrumbs": ["Home", "Login", "Register"],
        "workflow": "AUTHENTICATION",
        "workflow_step": "USER_SIGNUP",
        "parameters": [],
        "validation_rules": {"full_name": "REQUIRED", "phone": "REQUIRED_PHONE"},
        "requires_auth": False,
        "permissions": [],
        "feature_flags": [],
        "allowed_transitions": ["/login", "/dashboard"],
        "previous_routes": ["/login"],
        "next_routes": ["/dashboard"],
        "shortcut_routes": ["/login"],
        "recovery_routes": ["/login"],
        "page_capabilities": ["USER_REGISTRATION"],
        "supported_ai_actions": ["NAVIGATE", "INPUT_REGISTRATION", "SUBMIT_SIGNUP"],
        "visible_regions": ["header", "signup_card", "footer"],
        "primary_actions": ["SUBMIT_SIGNUP"],
        "secondary_actions": ["GOTO_LOGIN"],
        "forms": ["form_signup"],
        "buttons": ["btn_submit_signup", "btn_goto_login"],
        "dropdowns": [],
        "filters": [],
        "cards": ["card_signup_box"],
        "tables": [],
        "dialogs": [],
        "tabs": [],
        "accordions": [],
        "search_boxes": [],
        "uploads": [],
        "downloads": [],
        "metadata_version": "4.1",
        "updated_at": "2026-07-31T22:50:00Z",
    },
    {
        "path": "/dashboard",
        "name": "Dashboard",
        "page_type": "DASHBOARD",
        "semantic_label": "User Account & Order History Portal",
        "description": "User portal for viewing past orders, saved kundalis, and profile details.",
        "parent": "/",
        "children": [],
        "breadcrumbs": ["Home", "Dashboard"],
        "workflow": "USER_PROFILE",
        "workflow_step": "VIEW_DASHBOARD",
        "parameters": [],
        "validation_rules": {},
        "requires_auth": True,
        "permissions": [],
        "feature_flags": [],
        "allowed_transitions": ["/", "/puja", "/kundali"],
        "previous_routes": ["/"],
        "next_routes": ["/puja", "/kundali"],
        "shortcut_routes": ["/puja"],
        "recovery_routes": ["/"],
        "page_capabilities": ["ORDER_HISTORY", "PROFILE_EDITING", "KUNDALI_SAVED_REPORTS"],
        "supported_ai_actions": ["NAVIGATE", "SWITCH_TAB", "CANCEL_ORDER"],
        "visible_regions": ["header", "profile_summary_card", "tabs_navigation", "orders_table", "footer"],
        "primary_actions": ["VIEW_BOOKINGS"],
        "secondary_actions": ["UPDATE_PROFILE"],
        "forms": ["form_user_profile"],
        "buttons": ["btn_tab_orders", "btn_tab_kundalis", "btn_tab_settings"],
        "dropdowns": [],
        "filters": ["filter_order_status"],
        "cards": ["card_user_stats", "card_recent_booking"],
        "tables": ["table_user_orders"],
        "dialogs": [],
        "tabs": ["tab_orders", "tab_kundalis", "tab_settings"],
        "accordions": [],
        "search_boxes": [],
        "uploads": [],
        "downloads": [],
        "metadata_version": "4.1",
        "updated_at": "2026-07-31T22:50:00Z",
    },
]


class RouteDiscoveryEngine:
    """Engine responsible for discovering frontend routes and parsing site metadata."""

    def __init__(self, routes_spec: list[dict[str, Any]] | None = None) -> None:
        self._raw_routes = routes_spec if routes_spec is not None else DEFAULT_FRONTEND_ROUTES

    def discover_routes(self) -> list[dict[str, Any]]:
        """Return discovered route specification dictionary list."""
        logger.debug("Discovered %d frontend routes with UI metadata", len(self._raw_routes))
        return self._raw_routes

    def to_website_nodes(self) -> list[WebsiteNode]:
        """Convert discovered route specifications into WebsiteNode domain models."""
        nodes = []
        for item in self._raw_routes:
            node = WebsiteNode(
                url=item["path"],
                name=item["name"],
                node_type=NavigationNodeType.PAGE,
                metadata={
                    "page_type": item.get("page_type", "PAGE"),
                    "semantic_label": item.get("semantic_label", item["name"]),
                    "description": item.get("description", ""),
                    "parent": item.get("parent"),
                    "children": item.get("children", []),
                    "breadcrumbs": item.get("breadcrumbs", []),
                    "workflow": item.get("workflow"),
                    "workflow_step": item.get("workflow_step"),
                    "parameters": item.get("parameters", []),
                    "validation_rules": item.get("validation_rules", {}),
                    "requires_auth": item.get("requires_auth", False),
                    "permissions": item.get("permissions", []),
                    "feature_flags": item.get("feature_flags", []),
                    "allowed_transitions": item.get("allowed_transitions", []),
                    "previous_routes": item.get("previous_routes", []),
                    "next_routes": item.get("next_routes", []),
                    "shortcut_routes": item.get("shortcut_routes", []),
                    "recovery_routes": item.get("recovery_routes", []),
                    "page_capabilities": item.get("page_capabilities", []),
                    "supported_ai_actions": item.get("supported_ai_actions", []),
                    "visible_regions": item.get("visible_regions", []),
                    "primary_actions": item.get("primary_actions", []),
                    "secondary_actions": item.get("secondary_actions", []),
                    "forms": item.get("forms", []),
                    "buttons": item.get("buttons", []),
                    "dropdowns": item.get("dropdowns", []),
                    "filters": item.get("filters", []),
                    "cards": item.get("cards", []),
                    "tables": item.get("tables", []),
                    "dialogs": item.get("dialogs", []),
                    "tabs": item.get("tabs", []),
                    "accordions": item.get("accordions", []),
                    "search_boxes": item.get("search_boxes", []),
                    "uploads": item.get("uploads", []),
                    "downloads": item.get("downloads", []),
                    "metadata_version": item.get("metadata_version", "4.1"),
                    "updated_at": item.get("updated_at", "2026-07-31T22:50:00Z"),
                },
            )
            nodes.append(node)
        return nodes
